### ISSUE TITLE
First try with Terraform v0.9: The property 'tests' is not defined for Terraform::Group

### ISSUE THREAD

**Issue by toddmichael** [newcontext-oss/kitchen-terraform#118]
First attempt with Terraform 0.9.3 (latest) since receiving recent update that 0.9 is now supported. Thanks for that.  Getting errors when I try to perform initial sanity check via `kitchen list`
```
$ kitchen list
/Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:206:in `fail_no_property_error!': The property 'tests' is not defined for Terraform::Group. (NoMethodError)
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:184:in `assert_property_exists!'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:136:in `[]='
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/extensions/coercion.rb:44:in `set_value_with_coercion'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:179:in `block in initialize_attributes'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:178:in `each_pair'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:178:in `initialize_attributes'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/hashie-3.5.5/lib/hashie/dash.rb:110:in `initialize'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/group.rb:58:in `initialize'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/groups_coercer.rb:25:in `new'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/groups_coercer.rb:25:in `block in coerce'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/groups_coercer.rb:24:in `map'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/groups_coercer.rb:24:in `coerce'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/simple_config.rb:23:in `block in configure_required'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/configurable.rb:296:in `block in validate_config!'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/configurable.rb:295:in `each'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/configurable.rb:295:in `validate_config!'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/configurable.rb:51:in `finalize_config!'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/kitchen-inspec-0.18.0/lib/kitchen/verifier/inspec.rb:49:in `finalize_config!'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:348:in `setup_verifier'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:106:in `initialize'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:245:in `new'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:245:in `new_instance'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:142:in `block in build_instances'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in `map'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in `with_index'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in `build_instances'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:117:in `instances'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:112:in `filtered_instances'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:142:in `parse_subcommand'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/command/list.rb:30:in `call'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:121:in `list'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
	from /Users/tmichael/.gem/ruby/2.3.1/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
	from /Users/tmichael/.gem/ruby/2.3.1/bin/kitchen:23:in `load'
	from /Users/tmichael/.gem/ruby/2.3.1/bin/kitchen:23:in `<main>'
```
Not sure at this point if I've done something wrong or if it's a bug. Assuming the former, I bounced over to an older project that I last used successfully with Kitchen Terraform (circa 0.3), updated the bundle to use latest/greatest, re-ran and got this same error. I checked doc to confirm no breaking changes since 0.3.0 so now suspecting I may have hit a bug.  Appreciate the help

**Comment by ncs-alane** [comment]
@toddmichael: can you share the `groups` option from the `verifier` section of your `.kitchen.yml`?

**Comment by toddmichael** [comment]
@ncs-alane your question helped me solve the issue.  I had
```
  groups:
  - name: default
    tests:
      - ecs_cluster
```
I went back and read the latest examples and I see that we now need `controls`. I guess this was a change between 0.3 and 0.7.  Anyway, appreciate your help.  Closing issue as resolved/pebkac!  Cheers.
