### ISSUE TITLE
Path to Terraform CLI is not validated

### ISSUE THREAD

**Issue by danehammer** [newcontext-oss/kitchen-terraform#120]
It seems obvious I would need to install terraform first, but it was not what occurred to me when I saw the error. Without it installed, you get:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::StandardError
>>>>>> Message: ` version` failed: "No such file or directory - version"
>>>>>> ----------------------
```
With a stacktrace of:
```
E, [2017-05-28T23:05:33.281908 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/shell_out.rb:55:in `rescue in run_command'
E, [2017-05-28T23:05:33.281920 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/shell_out.rb:52:in `run_command'
E, [2017-05-28T23:05:33.281934 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/shell_out.rb:27:in `execute'
E, [2017-05-28T23:05:33.281946 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/client.rb:74:in `execute'
E, [2017-05-28T23:05:33.281957 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/terraform/client.rb:53:in `version'
E, [2017-05-28T23:05:33.281969 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/kitchen/driver/terraform.rb:72:in `version'
E, [2017-05-28T23:05:33.281981 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/kitchen/driver/terraform.rb:63:in `verify_supported_version'
E, [2017-05-28T23:05:33.281992 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/kitchen-terraform-0.7.0/lib/kitchen/driver/terraform.rb:43:in `verify_dependencies'
E, [2017-05-28T23:05:33.282004 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/driver.rb:43:in `for_plugin'
E, [2017-05-28T23:05:33.282022 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:233:in `new_driver'
E, [2017-05-28T23:05:33.282035 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:246:in `new_instance'
E, [2017-05-28T23:05:33.282047 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:142:in `block in build_instances'
E, [2017-05-28T23:05:33.282059 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:141:in `map'
E, [2017-05-28T23:05:33.282074 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:141:in `with_index'
E, [2017-05-28T23:05:33.282084 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:141:in `build_instances'
E, [2017-05-28T23:05:33.282096 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/config.rb:117:in `instances'
E, [2017-05-28T23:05:33.282107 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2017-05-28T23:05:33.282119 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2017-05-28T23:05:33.282130 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/command/action.rb:35:in `block in call'
E, [2017-05-28T23:05:33.282142 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-05-28T23:05:33.282152 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/command/action.rb:34:in `call'
E, [2017-05-28T23:05:33.282163 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:53:in `perform'
E, [2017-05-28T23:05:33.282173 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
E, [2017-05-28T23:05:33.282184 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
E, [2017-05-28T23:05:33.282230 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-05-28T23:05:33.282244 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/cli.rb:334:in `invoke_task'
E, [2017-05-28T23:05:33.282256 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
E, [2017-05-28T23:05:33.282267 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
E, [2017-05-28T23:05:33.282279 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/bin/kitchen:13:in `block in <top (required)>'
E, [2017-05-28T23:05:33.282291 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-05-28T23:05:33.282302 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/gems/test-kitchen-1.15.0/bin/kitchen:13:in `<top (required)>'
E, [2017-05-28T23:05:33.282315 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/bin/kitchen:23:in `load'
E, [2017-05-28T23:05:33.282325 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/bin/kitchen:23:in `<main>'
E, [2017-05-28T23:05:33.282336 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
E, [2017-05-28T23:05:33.282347 #49265] ERROR -- Kitchen: /Users/martellus/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
E, [2017-05-28T23:05:33.282362 #49265] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by ncs-alane** [comment]
@danehammer:

I am trying to improve the actionable error output for kitchen-terraform 1.0, but you've also identified a bug with the logic to generate the default value of the `cli` configuration property! You should be very proud of your efforts. (^o^)

**Comment by ncs-alane** [comment]
This issue has regressed. :sob:
