### ISSUE TITLE
Terraform 0.11.0 not supported error

### ISSUE THREAD

**Issue by ryancurrah** [newcontext-oss/kitchen-terraform#156]
When I try to run `kitchen test --destroy always` kitchen-terraform does not support terraform version `0.11.0`. 

Ruby version: `2.3.3`
Kitchen version: `1.19.1`
Kitchen-terraform version: `2.1.0`
Terraform version: `0.11.0`

**Command output**

```bash
kitchen test --destroy always
-----> Starting Kitchen (v1.19.1)
       Terraform v0.11.0
       
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Terraform version 0.11.0 is not supported; upgrade to Terraform version ~> 0.10.2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Log file .kitchen/logs/kitchen.log**

```ruby
I, [2017-11-25T15:28:38.987127 #152]  INFO -- Kitchen: -----> Starting Kitchen (v1.19.1)
I, [2017-11-25T15:28:39.179255 #152]  INFO -- Kitchen: Terraform v0.11.0
I, [2017-11-25T15:28:39.179404 #152]  INFO -- Kitchen: 
E, [2017-11-25T15:28:39.191549 #152] ERROR -- Kitchen: ------Exception-------
E, [2017-11-25T15:28:39.191589 #152] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2017-11-25T15:28:39.191606 #152] ERROR -- Kitchen: Message: Terraform version 0.11.0 is not supported; upgrade to Terraform version ~> 0.10.2
E, [2017-11-25T15:28:39.191633 #152] ERROR -- Kitchen: ----------------------
E, [2017-11-25T15:28:39.191645 #152] ERROR -- Kitchen: ------Backtrace-------
E, [2017-11-25T15:28:39.191656 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/kitchen-terraform-2.1.0/lib/kitchen/driver/terraform.rb:193:in `block in verify_dependencies'
E, [2017-11-25T15:28:39.191668 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/dry-monads-0.4.0/lib/dry/monads/result.rb:159:in `or'
E, [2017-11-25T15:28:39.191699 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/kitchen-terraform-2.1.0/lib/kitchen/driver/terraform.rb:192:in `verify_dependencies'
E, [2017-11-25T15:28:39.191712 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/driver.rb:43:in `for_plugin'
E, [2017-11-25T15:28:39.191728 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:234:in `new_driver'
E, [2017-11-25T15:28:39.191754 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:247:in `new_instance'
E, [2017-11-25T15:28:39.191767 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:142:in `block in build_instances'
E, [2017-11-25T15:28:39.191778 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:141:in `map'
E, [2017-11-25T15:28:39.191804 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:141:in `with_index'
E, [2017-11-25T15:28:39.191817 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:141:in `build_instances'
E, [2017-11-25T15:28:39.191829 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/config.rb:117:in `instances'
E, [2017-11-25T15:28:39.191855 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2017-11-25T15:28:39.191867 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2017-11-25T15:28:39.191877 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/command/test.rb:40:in `block in call'
E, [2017-11-25T15:28:39.191888 #152] ERROR -- Kitchen: /usr/lib64/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-11-25T15:28:39.191906 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/command/test.rb:38:in `call'
E, [2017-11-25T15:28:39.191918 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/cli.rb:52:in `perform'
E, [2017-11-25T15:28:39.191929 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/cli.rb:245:in `test'
E, [2017-11-25T15:28:39.191971 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2017-11-25T15:28:39.191993 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2017-11-25T15:28:39.192005 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2017-11-25T15:28:39.192016 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2017-11-25T15:28:39.192028 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/bin/kitchen:13:in `block in <top (required)>'
E, [2017-11-25T15:28:39.192055 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2017-11-25T15:28:39.192073 #152] ERROR -- Kitchen: /usr/lib64/ruby/gems/2.3.0/gems/test-kitchen-1.19.1/bin/kitchen:13:in `<top (required)>'
E, [2017-11-25T15:28:39.192089 #152] ERROR -- Kitchen: /usr/bin/kitchen:22:in `load'
E, [2017-11-25T15:28:39.192100 #152] ERROR -- Kitchen: /usr/bin/kitchen:22:in `<main>'
E, [2017-11-25T15:28:39.192111 #152] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by ncs-alane** [comment]
@ryancurrah: thank you for your interest in the project!

Terraform v0.11.0 will be supported by kitchen-terraform v3.0.0 which I expect to release in the next couple of days. If you need to leverage the support right away, you can use the pending release branch targeted by #151. I will add instructions to that pull request for how to use the branch and how to view the documentation.

**Comment by ryancurrah** [comment]
Thanks for the quick reply. This is a great project thank you for it. 

No I dont need to upgrade to Terraform `0.11.0` right away. Maybe the error message could be more clear. 

For example...

```ruby
>>>>>> Message: Terraform version 0.11.0 is not supported; upgrade to Terraform version ~> 0.10.2
```

Could probably be something like...

```ruby
>>>>>> Message: Terraform version 0.11.0 is not supported; downgrade to Terraform version ~> 0.10.2
```

If you agree on the idea I could create a PR, exact wording can change.

**Comment by ncs-alane** [comment]
The wording has already been tweaked on the 3.0.0 branch: "Terraform vA.B.C is not supported; install Terraform ~> vX.Y.Z". My thinking was to change the wording so that the action was accurate without having to account for the specific action of upgrading or downgrading.

**Comment by ryancurrah** [comment]
Awesome! I think this issue can be closed. Thanks again!
