### ISSUE TITLE
Accessing state_file is no longer possible

### ISSUE THREAD

**Issue by howdoicomputer** [newcontext-oss/kitchen-terraform#202]
```
terraform_state = attribute 'terraform_state', {}

control 'state_file' do
  describe 'the Terraform state file' do
    subject { json(terraform_state).terraform_version }

    it('is accessible') { is_expected.to match(/\d+\.\d+\.\d+/) }
  end
end
```

Yields this stacktrace:

```Failures:

  1) the Terraform state file is accessible
     Failure/Error: ::File.method(m.to_sym).call(@path)

     TypeError:
       can't convert Inspec::Attribute::DEFAULT_ATTRIBUTE to IO (Inspec::Attribute::DEFAULT_ATTRIBUTE#to_io gives Inspec::Attribute::DEFAULT_ATTRIBUTE)
     # ./vendor/bundle/ruby/2.4.0/gems/train-0.32.0/lib/train/file/local.rb:10:in `file?'
     # ./vendor/bundle/ruby/2.4.0/gems/train-0.32.0/lib/train/file/local.rb:10:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/train-0.32.0/lib/train/file/local.rb:10:in `block (2 levels) in <class:Local>'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/resources/file.rb:52:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/resources/file.rb:52:in `block (2 levels) in <class:FileResource>'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/resources/json.rb:96:in `load_raw_from_file'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/resources/json.rb:77:in `load_raw_content'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/resources/json.rb:38:in `initialize'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/inspec/plugins/resource.rb:64:in `initialize'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/inspec/resource.rb:51:in `new'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/inspec/resource.rb:51:in `block (3 levels) in create_dsl'
     # ./test/integration/default/controls/state_file.rb:8:in `block (3 levels) in load_with_context'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/inspec/runner_rspec.rb:77:in `run'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/inspec/runner.rb:117:in `run_tests'
     # ./vendor/bundle/ruby/2.4.0/gems/inspec-1.51.0/lib/inspec/runner.rb:101:in `run'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-inspec-0.22.0/lib/kitchen/verifier/inspec.rb:95:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform.rb:113:in `block (2 levels) in call'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform/enumerate_groups_and_hostnames.rb:79:in `each_resolved_hostname_and_group'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform/enumerate_groups_and_hostnames.rb:44:in `block in call'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform/enumerate_groups_and_hostnames.rb:43:in `each'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform/enumerate_groups_and_hostnames.rb:43:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform.rb:98:in `block in call'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform.rb:115:in `tap'
     # ./vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.1.0/lib/kitchen/verifier/terraform.rb:115:in `call'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:443:in `block in verify_action'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:498:in `block in action'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:497:in `action'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:435:in `verify_action'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:368:in `block in transition_to'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `each'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `transition_to'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:157:in `verify'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `public_send'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
     # ./vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'```

**Comment by ncs-alane** [comment]
@howdoicomputer thank you for your interest in the project! :wave: 

The `terraform_state` attribute was automatically provide in previous releases of Kitchen-Terraform but it must now be declared as an Terraform output as you have stated. We plan to better advertise breaking changes like this in the future.

**Comment by howdoicomputer** [comment]
@ncs-alane I actually think the biggest problem was the error `can't convert Inspec::Attribute::DEFAULT_ATTRIBUTE to IO (Inspec::Attribute::DEFAULT_ATTRIBUTE#to_io gives Inspec::Attribute::DEFAULT_ATTRIBUTE`.

I'm only loosely familiar with Inspec attributes and googling information on Inspec attribute type errors didn't yield much.

It was only through reading through the commit history on kitchen-terraform and then finding the newly written guides did I find out that terraform_state was no longer a built-in attribute.

**Comment by edwardbartholomew** [comment]
@connaryscott Thank you for your interest in kitchen-terraform. That tutorial has been migrated to https://newcontext-oss.github.io/kitchen-terraform/tutorials/extensive_kitchen_terraform.html
