### ISSUE TITLE
Kitchen::ActionFailed - The init command expects at most one argument.

### ISSUE THREAD

**Issue by ibata** [newcontext-oss/kitchen-terraform#221]
running "kitchen create" fails today whereas it was working days ago.  It fails on terraform init. But running terraform init works. I'm suspecting some gem versioning update or some system updates. but I did not do anything since last time.

Sharing my log file and kitchen diagnose --all

```sh
$ vi .kitchen/logs/ktf-suite-terraform.log
---- End output of terraform init -input=false -lock=true -lock-timeout=0s -no-color -upgrade -force-copy -backend=true  -get=true -get-plugins=true -plugin-dir=/var/lib/jenkins/workspace/Testing Terraform Daily@2/.terraform/plugins/linux_amd64 -verify-plugins=true /var/lib/jenkins/workspace/Testing Terraform Daily@2 ----
Ran terraform init -input=false -lock=true -lock-timeout=0s -no-color -upgrade -force-copy -backend=true  -get=true -get-plugins=true -plugin-dir=/var/lib/jenkins/workspace/Testing Terraform Daily@2/.terraform/plugins/linux_amd64 -verify-plugins=true /var/lib/jenkins/workspace/Testing Terraform Daily@2 returned 1
E, [2018-04-11T01:06:45.749307 #9623] ERROR -- ktf-suite-terraform: ----------------------
E, [2018-04-11T01:06:45.749322 #9623] ERROR -- ktf-suite-terraform: ------Backtrace-------
E, [2018-04-11T01:06:45.749334 #9623] ERROR -- ktf-suite-terraform: /var/lib/jenkins/.chefdk/gem/ruby/2.4.0/gems/kitchen-terraform-3.3.0/lib/kitchen/driver/terraform.rb:231:in `rescue in create'
E, [2018-04-11T01:06:45.749346 #9623] ERROR -- ktf-suite-terraform: /var/lib/jenkins/.chefdk/gem/ruby/2.4.0/gems/kitchen-terraform-3.3.0/lib/kitchen/driver/terraform.rb:228:in `create'
E, [2018-04-11T01:06:45.749362 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `public_send'
E, [2018-04-11T01:06:45.749375 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `block in perform_action'
E, [2018-04-11T01:06:45.749386 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-04-11T01:06:45.749398 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-04-11T01:06:45.749410 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-04-11T01:06:45.749422 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
E, [2018-04-11T01:06:45.749434 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `perform_action'
E, [2018-04-11T01:06:45.749446 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:379:in `create_action'
E, [2018-04-11T01:06:45.749457 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-04-11T01:06:45.749469 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
E, [2018-04-11T01:06:45.749481 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-04-11T01:06:45.749493 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:124:in `create'
E, [2018-04-11T01:06:45.749508 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-04-11T01:06:45.749521 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-04-11T01:06:45.749533 #9623] ERROR -- ktf-suite-terraform: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-04-11T01:06:45.749545 #9623] ERROR -- ktf-suite-terraform: ----End Backtrace-----
E, [2018-04-11T01:06:45.749579 #9623] ERROR -- ktf-suite-terraform: ---Nested Exception---
E, [2018-04-11T01:06:45.749590 #9623] ERROR -- ktf-suite-terraform: Class: Kitchen::Terraform::Error
E, [2018-04-11T01:06:45.749602 #9623] ERROR -- ktf-suite-terraform: Message: Running command resulted in failure: Expected process to exit with [0], but received '1'
---- Begin output of terraform init -input=false -lock=true -lock-timeout=0s -no-color -upgrade -force-copy -backend=true  -get=true -get-plugins=true -plugin-dir=/var/lib/jenkins/workspace/Testing Terraform Daily@2/.terraform/plugins/linux_amd64 -verify-plugins=true /var/lib/jenkins/workspace/Testing Terraform Daily@2 ----
STDOUT:
STDERR: The init command expects at most one argument.

Usage: terraform init [options] [DIR]
```
```sh
$ kitchen diagnose --all
ubuntu@image-builder:/var/lib/jenkins/workspace/Testing Terraform Daily@2$ sudo kitchen diagnose --all
$$$$$$ Running command `terraform version`
       Terraform v0.11.3
       + provider.aws v1.14.0
       + provider.chef v0.1.0
       + provider.null v1.0.0
       + provider.random v1.2.0
       + provider.template v1.0.0

       Your version of Terraform is out of date! The latest version
       is 0.11.7. You can update by downloading from www.terraform.io/downloads.html
$$$$$$ Terraform v0.11.3 is supported
---
timestamp: 2018-04-11 01:14:08 UTC
kitchen_version: 1.19.2
plugins:
  driver:
    Terraform:
      class: Kitchen::Driver::Terraform
      version: 3.3.0
      api_version: 2
  provisioner:
    Terraform:
      class: Kitchen::Provisioner::Terraform
      version: 3.3.0
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.19.2
      api_version: 1
  verifier:
    Terraform:
      class: Kitchen::Verifier::Terraform
      version: 3.3.0
      api_version: 2
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: "/var/lib/jenkins/workspace/Testing Terraform Daily@2/.kitchen.yml"
    raw_data:
      driver:
        name: terraform
        command_timeout: 2400
        plugin_directory: ".terraform/plugins/linux_amd64/"
        variable_files:
        - lucibatademosidejenkins.tfvars
      provisioner:
        name: terraform
      transport:
        name: ssh
        ssh_key: "****"
      verifier:
        name: terraform
        sudo: false
      platforms:
      - name: terraform
      suites:
      - name: ktf_suite
        verifier:
          groups:
          - name: remote
            controls:
            - reach_host
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: terraform
        command_timeout: 2400
        plugin_directory: ".terraform/plugins/linux_amd64/"
        variable_files:
        - lucibatademosidejenkins.tfvars
      provisioner:
        name: terraform
      transport:
        name: ssh
        ssh_key: "****"
      verifier:
        name: terraform
        sudo: false
      platforms:
      - name: terraform
      suites:
      - name: ktf_suite
        verifier:
          groups:
          - name: remote
            controls:
            - reach_host
instances:
  ktf-suite-terraform:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_error: Kitchen::ActionFailed
    driver:
      backend_configurations: {}
      color: true
      command_timeout: 2400
      kitchen_root: "/var/lib/jenkins/workspace/Testing Terraform Daily@2"
      lock: true
      lock_timeout: 0
      log_level: :info
      name: terraform
      parallelism: 10
      plugin_directory: "/var/lib/jenkins/workspace/Testing Terraform Daily@2/.terraform/plugins/linux_amd64"
      pre_create_command:
      root_module_directory: "/var/lib/jenkins/workspace/Testing Terraform Daily@2"
      test_base_path: "/var/lib/jenkins/workspace/Testing Terraform Daily@2/test/integration"
      variable_files:
      - "/var/lib/jenkins/workspace/Testing Terraform Daily@2/lucibatademosidejenkins.tfvars"
      variables: {}
    provisioner:
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      kitchen_root: "/var/lib/jenkins/workspace/Testing Terraform Daily@2"
      max_retries: 1
      name: terraform
      retry_on_exit_code: []
      root_path: "/tmp/kitchen"
      sudo: true
      sudo_command: sudo -E
      test_base_path: "/var/lib/jenkins/workspace/Testing Terraform Daily@2/test/integration"
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/var/lib/jenkins/workspace/Testing Terraform Daily@2"
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_username:
      ssh_key: "****"
      test_base_path: "/var/lib/jenkins/workspace/Testing Terraform Daily@2/test/integration"
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      color: true
      command_prefix:
      debug:
      ftp_proxy:
      groups:
      - name: remote
        controls:
        - reach_host
      http_proxy:
      https_proxy:
      inspec_tests: []
      kitchen_root: "/var/lib/jenkins/workspace/Testing Terraform Daily@2"
      log_level: :info
      name: terraform
      root_path: "/tmp/verifier"
      sudo: false
      sudo_command: sudo -E
      suite_name: ktf_suite
      test_base_path: "/var/lib/jenkins/workspace/Testing Terraform Daily@2/test/integration"
```

**Comment by ibata** [comment]
i read that it could be related to specifying terraform bin path. Where should I do it? if on kitchen.yml then where and what's the command sample?

**Comment by ncs-alane** [comment]
@ibata I appologize for the inconvenience.

This failure is a result of the error "The init command expects at most one argument", which is caused by the execution of `terraform init -input=false -lock=true -lock-timeout=0s -no-color -upgrade -force-copy -backend=true -get=true -get-plugins=true -plugin-dir=/var/lib/jenkins/workspace/Testing Terraform Daily@2/.terraform/plugins/linux_amd64 -verify-plugins=true /var/lib/jenkins/workspace/Testing Terraform Daily@2`. 

The issue stems from the existence of space characters in the Kitchen root, `/var/lib/jenkins/workspace/Testing Terraform Daily@2` which is not being properly escaped by Kitchen-Terraform. As a workaround, you could try renaming the directory to not include space characters.

**Comment by ibata** [comment]
@ncs-alane thank you again for responding so fast. and thank you for filing a bug.
