### ISSUE TITLE
Receive 'Interrupt received' signal after 11m20s

### ISSUE THREAD

**Issue by darkraiden** [newcontext-oss/kitchen-terraform#255]
Hello there,

I've been experiencing something odd whilst testing a terraform module I wrote with test kitchen.

## Ruby, terraform and gems versions

* ruby 2.4.2
* kitchen-terraform 3.3
* test-kitchen 1.22.0
* terraform v0.11.7
* provider.aws v1.29.0

## Context

I wrote a module to provision an RDS instance to AWS - run `kitchen converge` and start provisioning. Everything looks fine until it gets to 11m20s, then it fails throwing this error:

```bash
       module.rds-master.aws_db_instance.rds: Still creating... (10m50s elapsed)
       module.rds-master.aws_db_instance.rds: Still creating... (11m0s elapsed)
       module.rds-master.aws_db_instance.rds: Still creating... (11m10s elapsed)
       module.rds-master.aws_db_instance.rds: Still creating... (11m20s elapsed)
       Interrupt received.
       Please wait for Terraform to exit or data loss may occur.
       Gracefully shutting down...
       stopping operation...

       Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-aws>.  Please see .kitchen/logs/default-aws.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

and this is the content of the log file:

```
^[[0m^[[1mmodule.rds-master.aws_db_instance.rds: Still creating... (10m50s elapsed)^[[0m^[[0m
^[[0m^[[1mmodule.rds-master.aws_db_instance.rds: Still creating... (11m0s elapsed)^[[0m^[[0m
^[[0m^[[1mmodule.rds-master.aws_db_instance.rds: Still creating... (11m10s elapsed)^[[0m^[[0m
^[[0m^[[1mmodule.rds-master.aws_db_instance.rds: Still creating... (11m20s elapsed)^[[0m^[[0m
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
stopping operation...
^[[0m^[[1m^[[32m
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.^[[0m
STDERR:
---- End output of terraform apply -lock=true -lock-timeout=0s -input=false -auto-approve=true  -parallelism=10 -refresh=true   /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/test/test_fixture ----
Ran terraform apply -lock=true -lock-timeout=0s -input=false -auto-approve=true  -parallelism=10 -refresh=true   /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/test/test_fixture returned 0
E, [2018-07-30T15:37:01.720184 #15338] ERROR -- default-aws: ----------------------
E, [2018-07-30T15:37:01.720221 #15338] ERROR -- default-aws: ------Backtrace-------
E, [2018-07-30T15:37:01.720255 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.3.1/lib/kitchen/provisioner/terraform.rb:106:in `rescue in call'
E, [2018-07-30T15:37:01.720290 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/kitchen-terraform-3.3.1/lib/kitchen/provisioner/terraform.rb:98:in `call'
E, [2018-07-30T15:37:01.720324 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:393:in `block in converge_action'
E, [2018-07-30T15:37:01.720387 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-07-30T15:37:01.720423 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-07-30T15:37:01.720458 #15338] ERROR -- default-aws: /Users/davide/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-07-30T15:37:01.720493 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:497:in `action'
E, [2018-07-30T15:37:01.720527 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:389:in `converge_action'
E, [2018-07-30T15:37:01.720561 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-07-30T15:37:01.720603 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `each'
E, [2018-07-30T15:37:01.720639 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-07-30T15:37:01.720673 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/instance.rb:135:in `converge'
E, [2018-07-30T15:37:01.720707 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-07-30T15:37:01.720741 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-07-30T15:37:01.720776 #15338] ERROR -- default-aws: /Users/davide/wip/docker-build/workspace/modules/database/rds/rds-master/vendor/bundle/ruby/2.4.0/gems/test-kitchen-1.22.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-07-30T15:37:01.720810 #15338] ERROR -- default-aws: ----End Backtrace-----
```

The same happened with an `ElastiCache` module, still failing at 11m20s mark. For more context, find below the files used for this test:

### kitchen.yml

```yml
---
driver:
  name: "terraform"
  root_module_directory: "test/test_fixture"

provisioner:
  name: "terraform"

platforms:
  - name: "aws"

verifier:
  name: "awspec"

suites:
  - name: "default"
```

### module.tf

```hcl
resource "aws_db_instance" "rds" {
  identifier = "${var.environment}-${var.service}-${var.engine}-master"

  engine         = "${var.engine}"
  engine_version = "${var.engine_version}"
  instance_class = "${var.instance_class}"

  storage_type      = "${var.storage_type}"
  allocated_storage = "${var.allocated_storage}"

  iops = "${var.storage_type == "io1" ?
    var.iops != 0 ?
      var.iops :
      var.allocated_storage * 50 :
    0
  }"

  name     = "${var.db_name}"
  username = "${var.db_username}"
  password = "${var.db_password}"
  port     = "${var.db_port}"

  vpc_security_group_ids = ["${var.vpc_security_group_ids}"]
  db_subnet_group_name   = "${var.subnet_group_name}"
  parameter_group_name   = "${var.parameter_group_name}"

  multi_az            = "${var.is_multi_az}"
  publicly_accessible = "${var.is_publicly_accessible}"

  allow_major_version_upgrade = "${var.allow_major_version_upgrade}"
  auto_minor_version_upgrade  = "${var.auto_minor_version_upgrade}"
  apply_immediately           = "${var.apply_immediately}"
  maintenance_window          = "${var.maintenance_window}"

  final_snapshot_identifier = "${var.environment}-${var.service}-${var.engine}-master-${md5(timestamp())}"

  backup_retention_period = "${var.backup_retention_period}"
  backup_window           = "${var.backup_window}"

  tags = "${
    merge(
      map("Name", format("%s-%s-%s-master", var.environment, var.service, var.engine)),
      map("Environment", var.environment),
      map("Service", var.service),
      map("Description", var.description),
      var.tags
    )
  }"
}
```

### test/test_fixture/main.tf

```hcl
provider "aws" {
  region = "us-east-1"
}

module "rds-master" {
  source         = "../../"
  environment    = "test"
  service        = "kitchen"
  engine         = "postgres"
  engine_version = "9.3"
  db_username    = "test"
  db_password    = "password"
  db_port        = 5432
}
```

Just FYI if I run this `test/test_fixture/main.tf` file using terraform commands (`init`, `plan` and `apply`) works like a charm.

Any help would be greatly appreciated. Thanks in advance 🙂

**Comment by edwardbartholomew** [comment]
Greetings @darkraiden and thanks for your interest in kitchen-terraform!

I believe you are running into a timeout by kitchen-terraform. There is a configuration attribute called "command_timeout" that defaults to 600 seconds. This attribute is in the driver section of .kitchen.yml - you could find example on that attribute being set in the OpenStack tutorial's .kitchen.yml - https://newcontext-oss.github.io/kitchen-terraform/tutorials/openstack_provider.html

If you want to give that a try and let us know, we can help further if doesn't solve your issue.

**Comment by darkraiden** [comment]
Thanks for replying so quickly. I imagined it might have been a timeout issue but couldn't find any reference to it. That's brilliant, I'll give it a go and let you know whether it works. Cheers

**Comment by darkraiden** [comment]
@edwardbartholomew that worked as expected. Thanks a lot for your help, my bad not finding any reference to the `command_timeout`.

**Comment by ncs-alane** [comment]
The `command_timeout` attribute is described in the driver documentation: https://www.rubydoc.info/gems/kitchen-terraform/Kitchen/Driver/Terraform. 

I think we need to move the user facing documentation out of RubyDoc and in to GitHub Pages, though I'm not sure if we'll be able to retain a search function with that move. 🤔
