### ISSUE TITLE
[terraform 0.12.4]  Message: nomad: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by lmayorga1980** [newcontext-oss/kitchen-terraform#353]
Using `Terraform 0.12.4` and seems like there is an issue with `kitchen-terraform`.

**kitchen.yml**
```ruby
---
driver:
  name: terraform
  command_timeout: 1000
  variable_files:
    - my-variables.tfvars

provisioner:
  name: terraform

transport:
  name: ssh
  ssh_key: "~/.ssh/mykey.pem"
  username: ubuntu
  port: 22

platforms:
  - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: nomad
      backend: ssh
      hosts_output: nomad_server_ip
      key_files:
        - "~/.ssh/mykey.pem"
      controls:
        - operating_system
      user: ubuntu
      reporter:
        - progress

suites:
  - name: nomad

```

**Gemfile**
```
source "https://rubygems.org"

gem 'kitchen-terraform'
gem 'test-kitchen'
```

**kitchen-log**

```
I, [2019-07-17T10:38:47.031924 #22680]  INFO -- Kitchen: -----> Starting Kitchen (v2.2.5)
I, [2019-07-17T10:38:48.735512 #22680]  INFO -- Kitchen: -----> Verifying <nomad-ubuntu>...
W, [2019-07-17T10:38:48.775151 #22680]  WARN -- Kitchen: Running command `terraform output -json` in directory /home/lcentinel/gitcom/terraform/nomad
E, [2019-07-17T10:38:48.825037 #22680] ERROR -- Kitchen: ------Exception-------
E, [2019-07-17T10:38:48.825078 #22680] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-07-17T10:38:48.825098 #22680] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Verify failed on instance <nomad-ubuntu>.  Please see .kitchen/logs/nomad-ubuntu.log for more details
E, [2019-07-17T10:38:48.825152 #22680] ERROR -- Kitchen: ----------------------
E, [2019-07-17T10:38:48.825169 #22680] ERROR -- Kitchen: ------Backtrace-------
E, [2019-07-17T10:38:48.825186 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:183:in `report_errors'
E, [2019-07-17T10:38:48.825210 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:174:in `run_action'
E, [2019-07-17T10:38:48.825227 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:36:in `block in call'
E, [2019-07-17T10:38:48.825243 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-07-17T10:38:48.825262 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:34:in `call'
E, [2019-07-17T10:38:48.825279 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:52:in `perform'
E, [2019-07-17T10:38:48.825295 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2019-07-17T10:38:48.825312 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2019-07-17T10:38:48.825352 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-07-17T10:38:48.825369 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2019-07-17T10:38:48.825385 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2019-07-17T10:38:48.825401 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/bin/kitchen:13:in `block in <top (required)>'
E, [2019-07-17T10:38:48.825417 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2019-07-17T10:38:48.825461 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/bin/kitchen:13:in `<top (required)>'
E, [2019-07-17T10:38:48.825478 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/bin/kitchen:23:in `load'
E, [2019-07-17T10:38:48.825495 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/bin/kitchen:23:in `<top (required)>'
E, [2019-07-17T10:38:48.825511 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
E, [2019-07-17T10:38:48.825528 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
E, [2019-07-17T10:38:48.825544 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
E, [2019-07-17T10:38:48.825560 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:424:in `exec'
E, [2019-07-17T10:38:48.825591 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
E, [2019-07-17T10:38:48.825608 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-07-17T10:38:48.825659 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
E, [2019-07-17T10:38:48.825676 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
E, [2019-07-17T10:38:48.825692 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
E, [2019-07-17T10:38:48.825709 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
E, [2019-07-17T10:38:48.825725 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/bin/bundle:30:in `block in <main>'
E, [2019-07-17T10:38:48.825742 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
E, [2019-07-17T10:38:48.825761 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/bin/bundle:22:in `<main>'
E, [2019-07-17T10:38:48.825779 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `eval'
E, [2019-07-17T10:38:48.825796 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `<main>'
E, [2019-07-17T10:38:48.825860 #22680] ERROR -- Kitchen: ----End Backtrace-----
E, [2019-07-17T10:38:48.825888 #22680] ERROR -- Kitchen: -Composite Exception--
E, [2019-07-17T10:38:48.825906 #22680] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2019-07-17T10:38:48.825923 #22680] ERROR -- Kitchen: Message: Verify failed on instance <nomad-ubuntu>.  Please see .kitchen/logs/nomad-ubuntu.log for more details
E, [2019-07-17T10:38:48.825939 #22680] ERROR -- Kitchen: ----------------------
E, [2019-07-17T10:38:48.825955 #22680] ERROR -- Kitchen: ------Backtrace-------
E, [2019-07-17T10:38:48.825971 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/kitchen-terraform-5.1.0/lib/kitchen/verifier/terraform.rb:109:in `rescue in call'
E, [2019-07-17T10:38:48.826036 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/kitchen-terraform-5.1.0/lib/kitchen/verifier/terraform.rb:102:in `call'
E, [2019-07-17T10:38:48.826054 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:459:in `block in verify_action'
E, [2019-07-17T10:38:48.826070 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2019-07-17T10:38:48.826087 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:514:in `block in action'
E, [2019-07-17T10:38:48.826103 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-07-17T10:38:48.826119 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:513:in `action'
E, [2019-07-17T10:38:48.826135 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:451:in `verify_action'
E, [2019-07-17T10:38:48.826154 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-07-17T10:38:48.826170 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-07-17T10:38:48.826272 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-07-17T10:38:48.826290 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `each'
E, [2019-07-17T10:38:48.826308 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-07-17T10:38:48.826332 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:162:in `verify'
E, [2019-07-17T10:38:48.826357 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `public_send'
E, [2019-07-17T10:38:48.826381 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-07-17T10:38:48.826398 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-07-17T10:38:48.826416 #22680] ERROR -- Kitchen: ----End Backtrace-----
E, [2019-07-17T10:38:48.826432 #22680] ERROR -- Kitchen: ---Nested Exception---
E, [2019-07-17T10:38:48.826480 #22680] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-07-17T10:38:48.826497 #22680] ERROR -- Kitchen: Message: nomad: no implicit conversion of Array into String
E, [2019-07-17T10:38:48.826544 #22680] ERROR -- Kitchen: ----------------------
E, [2019-07-17T10:38:48.826561 #22680] ERROR -- Kitchen: ------Backtrace-------
E, [2019-07-17T10:38:48.826578 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/kitchen-terraform-5.1.0/lib/kitchen/verifier/terraform.rb:109:in `rescue in call'
E, [2019-07-17T10:38:48.826595 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/kitchen-terraform-5.1.0/lib/kitchen/verifier/terraform.rb:102:in `call'
E, [2019-07-17T10:38:48.826612 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:459:in `block in verify_action'
E, [2019-07-17T10:38:48.826630 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2019-07-17T10:38:48.826679 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:514:in `block in action'
E, [2019-07-17T10:38:48.826696 #22680] ERROR -- Kitchen: /home/lcentinel/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-07-17T10:38:48.826712 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:513:in `action'
E, [2019-07-17T10:38:48.826728 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:451:in `verify_action'
E, [2019-07-17T10:38:48.826744 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-07-17T10:38:48.826760 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-07-17T10:38:48.826808 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-07-17T10:38:48.826833 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `each'
E, [2019-07-17T10:38:48.826858 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-07-17T10:38:48.826942 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/instance.rb:162:in `verify'
E, [2019-07-17T10:38:48.826983 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `public_send'
E, [2019-07-17T10:38:48.827002 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-07-17T10:38:48.827020 #22680] ERROR -- Kitchen: /home/lcentinel/gitcom/terraform/nomad/vendor/bundle/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-07-17T10:38:48.827064 #22680] ERROR -- Kitchen: ----End Backtrace-----

```

**Comment by aaron-lane** [comment]
Hello again, @lmayorga1980!

I apologize for the frustrating experience.

While the error messages are not particularly helpful, what stands out to me is the following line:

> E, [2019-07-17T10:38:48.826497 #22680] ERROR -- Kitchen: Message: nomad: no implicit conversion of Array into String

This message indicates that an array or list was improperly used in place of a string while verifying the system named "nomad" [1]. I suspect this error may be generated by the content of the `operating_system` control because Kitchen-Terraform is designed to convert all input objects to expected classes. Can you share the content of that control file?

I have opened #354 to track the effort to improve error messages in order to help clarify problems like this in the future, regardless of the source.

[1]: https://github.com/newcontext-oss/kitchen-terraform/blob/master/lib/kitchen/terraform/system.rb#L78

**Comment by lmayorga1980** [comment]
Working now.
