### ISSUE TITLE
Message: Terraform v0.12.6 is not supported; install Terraform ~> v0.11.4

### ISSUE THREAD

**Issue by lmayorga1980** [newcontext-oss/kitchen-terraform#356]
**Terraform Version**: 0.12.6

**Gemfile**

```ruby
source "https://rubygems.org/"

gem 'kitchen-terraform'
gem 'test-kitchen'

```

**kitchen-error**

```
E, [2019-08-13T17:27:37.462955 #40786] ERROR -- project-ubuntu: ----------------------
E, [2019-08-13T17:27:37.462975 #40786] ERROR -- project-ubuntu: ------Backtrace-------
E, [2019-08-13T17:27:37.462995 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/kitchen-terraform-4.3.0/lib/kitchen/driver/terraform.rb:263:in `rescue in destroy'
E, [2019-08-13T17:27:37.463016 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/kitchen-terraform-4.3.0/lib/kitchen/driver/terraform.rb:255:in `destroy'
E, [2019-08-13T17:27:37.463038 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:484:in `public_send'
E, [2019-08-13T17:27:37.463059 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:484:in `block in perform_action'
E, [2019-08-13T17:27:37.463080 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:548:in `block in synchronize_or_call'
E, [2019-08-13T17:27:37.463101 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:546:in `synchronize'
E, [2019-08-13T17:27:37.463127 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:546:in `synchronize_or_call'
E, [2019-08-13T17:27:37.463148 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:513:in `block in action'
E, [2019-08-13T17:27:37.463170 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-08-13T17:27:37.463191 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:512:in `action'
E, [2019-08-13T17:27:37.463212 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:484:in `perform_action'
E, [2019-08-13T17:27:37.463233 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:471:in `destroy_action'
E, [2019-08-13T17:27:37.463255 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-08-13T17:27:37.463276 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-08-13T17:27:37.463297 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-08-13T17:27:37.463330 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `each'
E, [2019-08-13T17:27:37.463408 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-08-13T17:27:37.463440 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:173:in `destroy'
E, [2019-08-13T17:27:37.463463 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:189:in `block in test'
E, [2019-08-13T17:27:37.463485 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-08-13T17:27:37.463506 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/instance.rb:187:in `test'
E, [2019-08-13T17:27:37.463527 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `public_send'
E, [2019-08-13T17:27:37.463549 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-08-13T17:27:37.463570 #40786] ERROR -- project-ubuntu: /Users/user/.rvm/gems/ruby-2.5.3/gems/test-kitchen-1.24.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-08-13T17:27:37.463592 #40786] ERROR -- project-ubuntu: ----End Backtrace-----```

**Comment by lmayorga1980** [comment]
Terraform binary was 0.12.x but the syntax was 0.11.
