### ISSUE TITLE
gem mixlib-shellout (~> 2.2) to conservative for chef-workstation

### ISSUE THREAD

**Issue by ehaselwanter** [newcontext-oss/kitchen-terraform#381]
with 

```
chef -v
Chef Workstation version: 0.13.35
Chef Infra Client version: 15.6.10
Chef InSpec version: 4.18.39
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.16.11
```

and

```
chef gem install kitchen-terraform
Fetching dry-logic-0.6.1.gem
Fetching dry-types-0.14.1.gem
Fetching dry-core-0.4.9.gem
Fetching dry-configurable-0.9.0.gem
Fetching dry-equalizer-0.3.0.gem
Fetching dry-inflector-0.2.0.gem
Fetching dry-container-0.7.2.gem
Fetching dry-validation-0.13.3.gem
Fetching kitchen-terraform-5.1.1.gem
Fetching mixlib-shellout-2.4.4.gem
Fetching tty-which-0.4.2.gem
WARNING:  You don't have /Users/eh/.chefdk/gem/ruby/2.6.0/bin in your PATH,
	  gem executables will not run.
Successfully installed dry-core-0.4.9
Successfully installed dry-configurable-0.9.0
Successfully installed dry-equalizer-0.3.0
Successfully installed dry-logic-0.6.1
Successfully installed dry-inflector-0.2.0
Successfully installed dry-container-0.7.2
Successfully installed dry-types-0.14.1
Successfully installed dry-validation-0.13.3
Successfully installed mixlib-shellout-2.4.4
Successfully installed tty-which-0.4.2
Successfully installed kitchen-terraform-5.1.1
11 gems installed
```

I get

```
E, [2020-01-28T09:29:26.399290 #51569] ERROR -- Kitchen: ---Nested Exception---
E, [2020-01-28T09:29:26.399301 #51569] ERROR -- Kitchen: Class: Gem::ConflictError
E, [2020-01-28T09:29:26.399311 #51569] ERROR -- Kitchen: Message: Unable to activate kitchen-terraform-5.1.1, because mixlib-shellout-3.0.7 conflicts with mixlib-shellout (~> 2.2)
E, [2020-01-28T09:29:26.399321 #51569] ERROR -- Kitchen: ----------------------
E, [2020-01-28T09:29:26.399332 #51569] ERROR -- Kitchen: ------Backtrace-------
```

So I **mixlib-shellout (~> 2.2)** in the runtime deps is not working with chef-workstation out of the box.

**Comment by aaron-lane** [comment]
Hi @ehaselwanter! Thank you for your interest in the project.

I recommend that you use Bundler to install and execute Kitchen-Terraform, as mentioned in the ReadMe. Bundler should ensure that conflicting versions of gems are not invoked simultaneously.

**Comment by ehaselwanter** [comment]
well. that obviously works. I just would like to do it the same way as with our other tools integration. we already have a docker image with terraform and chef-workstation installed. would be nice to *not* use a different approach here (using `bundle exec` I mean)

**Comment by ehaselwanter** [comment]
@aaron-lane this is starting to feel like yak shaving: no I need to have compiler/dev-tool dependencies all over the place :-(

**Comment by aaron-lane** [comment]
Can you clarify what you mean by your latest comment? Development dependencies should not be included when you install Kitchen-Terraform using Bundler. 🤔

**Comment by aaron-lane** [comment]
Any way, I will see if we can easily increase the version of mixlib-shellout to solve your issue.

**Comment by ehaselwanter** [comment]
well, native extensions in the Gem dependencies:

this is what I get with bundle install:

```bash
cat Gemfile
source 'https://rubygems.org/' do
  gem(
    'kitchen-terraform',
    '~> 5.1'
  )
end
```

```bash
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Using concurrent-ruby 1.1.5
Fetching i18n 1.8.2
Installing i18n 1.8.2
Fetching minitest 5.14.0
Installing minitest 5.14.0
Using thread_safe 0.3.6
Fetching tzinfo 1.2.6
Installing tzinfo 1.2.6
Fetching activesupport 5.2.4.1
Installing activesupport 5.2.4.1
Fetching public_suffix 4.0.3
Installing public_suffix 4.0.3
Fetching addressable 2.7.0
Installing addressable 2.7.0
Using aws-eventstream 1.0.3
Fetching aws-partitions 1.270.0
Installing aws-partitions 1.270.0
Using aws-sigv4 1.1.0
Using jmespath 1.4.0
Fetching aws-sdk-core 3.89.1
Installing aws-sdk-core 3.89.1
Using aws-sdk-apigateway 1.36.0
Using aws-sdk-apigatewayv2 1.15.0
Using aws-sdk-athena 1.22.0
Using aws-sdk-autoscaling 1.22.0
Using aws-sdk-budgets 1.27.0
Using aws-sdk-cloudformation 1.29.0
Using aws-sdk-cloudhsm 1.19.0
Fetching aws-sdk-cloudhsmv2 1.20.0
Installing aws-sdk-cloudhsmv2 1.20.0
Using aws-sdk-cloudtrail 1.20.0
Fetching aws-sdk-cloudwatch 1.32.0
Installing aws-sdk-cloudwatch 1.32.0
Fetching aws-sdk-cloudwatchlogs 1.28.0
Installing aws-sdk-cloudwatchlogs 1.28.0
Using aws-sdk-codecommit 1.30.0
Using aws-sdk-codedeploy 1.27.0
Fetching aws-sdk-codepipeline 1.28.0
Installing aws-sdk-codepipeline 1.28.0
Using aws-sdk-configservice 1.40.0
Using aws-sdk-costandusagereportservice 1.18.0
Using aws-sdk-dynamodb 1.41.0
Fetching aws-sdk-ec2 1.139.0
Installing aws-sdk-ec2 1.139.0
Fetching aws-sdk-ecr 1.24.0
Installing aws-sdk-ecr 1.24.0
Fetching aws-sdk-ecs 1.57.0
Installing aws-sdk-ecs 1.57.0
Fetching aws-sdk-eks 1.31.0
Installing aws-sdk-eks 1.31.0
Using aws-sdk-elasticache 1.29.0
Using aws-sdk-elasticbeanstalk 1.26.0
Using aws-sdk-elasticloadbalancing 1.19.0
Using aws-sdk-elasticloadbalancingv2 1.39.0
Using aws-sdk-elasticsearchservice 1.29.0
Using aws-sdk-firehose 1.24.0
Fetching aws-sdk-iam 1.33.0
Installing aws-sdk-iam 1.33.0
Fetching aws-sdk-kafka 1.17.0
Installing aws-sdk-kafka 1.17.0
Using aws-sdk-kinesis 1.20.0
Fetching aws-sdk-kms 1.28.0
Installing aws-sdk-kms 1.28.0
Fetching aws-sdk-lambda 1.35.0
Installing aws-sdk-lambda 1.35.0
Using aws-sdk-organizations 1.17.0
Fetching aws-sdk-rds 1.76.0
Installing aws-sdk-rds 1.76.0
Fetching aws-sdk-redshift 1.36.0
Installing aws-sdk-redshift 1.36.0
Using aws-sdk-route53 1.30.0
Using aws-sdk-route53domains 1.18.0
Using aws-sdk-route53resolver 1.11.0
Fetching aws-sdk-s3 1.60.1
Installing aws-sdk-s3 1.60.1
Fetching aws-sdk-securityhub 1.17.0
Installing aws-sdk-securityhub 1.17.0
Using aws-sdk-ses 1.27.0
Using aws-sdk-sms 1.17.0
Using aws-sdk-sns 1.21.0
Using aws-sdk-sqs 1.23.1
Fetching aws-sdk-ssm 1.71.0
Installing aws-sdk-ssm 1.71.0
Using multipart-post 2.1.1
Fetching faraday 0.17.3
Installing faraday 0.17.3
Using unf_ext 0.0.7.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using timeliness 0.3.10
Using ms_rest 0.7.5
Using ms_rest_azure 0.11.1
Using azure_graph_rbac 0.17.1
Using azure_mgmt_key_vault 0.17.5
Using azure_mgmt_resources 0.17.8
Using azure_mgmt_security 0.18.0
Fetching azure_mgmt_storage 0.19.1
Installing azure_mgmt_storage 0.19.1
Using bcrypt_pbkdf 1.0.1
Using builder 3.2.4
Using bundler 1.17.2
Fetching chef-utils 15.7.32
Installing chef-utils 15.7.32
Using fuzzyurl 0.9.0
Using tomlrb 1.2.9
Fetching mixlib-config 3.0.6
Installing mixlib-config 3.0.6
Fetching mixlib-shellout 2.4.4
Installing mixlib-shellout 2.4.4
Fetching chef-config 15.7.32
Installing chef-config 15.7.32
Using libyajl2 1.2.0
Fetching ffi-yajl 2.3.3
Installing ffi-yajl 2.3.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/ffi-yajl-2.3.3/ext/ffi_yajl/ext/encoder
/opt/chef-workstation/embedded/bin/ruby -I
/opt/chef-workstation/embedded/lib/ruby/2.6.0 -r ./siteconf20200211-19-wjlyj.rb
extconf.rb
-I/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include
-I/opt/chef-workstation/embedded/include -O2 -D_FORTIFY_SOURCE=2
-fstack-protector -O3 -g -pipe -fPIC
-L/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib
-L. -Wl,-rpath,/opt/chef-workstation/embedded/lib
-L/opt/chef-workstation/embedded/lib -fstack-protector-strong -rdynamic
-Wl,-export-dynamic -L/opt/chef-workstation/embedded/lib 
-Wl,-rpath,/opt/chef-workstation/embedded/lib
checking for yajl/yajl_tree.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/chef-workstation/embedded/bin/$(RUBY_BASE_NAME)
/opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:478:in `try_do': The
compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:612:in `try_cpp'
from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:1173:in `block in
find_header'
from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:970:in `block in
checking_for'
from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:361:in `block (2
levels) in postpone'
	from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:331:in `open'
from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:361:in `block in
postpone'
	from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:969:in
`checking_for'
from /opt/chef-workstation/embedded/lib/ruby/2.6.0/mkmf.rb:1172:in
`find_header'
	from extconf.rb:37:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ffi-yajl-2.3.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/ffi-yajl-2.3.3 for
inspection.
Results logged to
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ffi-yajl-2.3.3/gem_make.out

An error occurred while installing ffi-yajl (2.3.3), and Bundler cannot
continue.
Make sure that `gem install ffi-yajl -v '2.3.3' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  kitchen-terraform was resolved to 5.1.1, which depends on
    inspec was resolved to 4.18.51, which depends on
      chef-telemetry was resolved to 1.0.2, which depends on
        ffi-yajl
ERROR: Job failed: exit code 1
```

**Comment by ehaselwanter** [comment]
@aaron-lane thx for merging. is releasing to ruby gems a manual task?

**Comment by aaron-lane** [comment]
No, I just need to refresh the gem certificate today. You can source the master branch if you don't want to wait for that to happen as the branch should remain stable until the release is complete.

**Comment by ehaselwanter** [comment]
thx. Included it and works nicely :-)
