### ISSUE TITLE
Kitchen verify errors out for Inspec 4.18 and Kitchen-terraform - Can't find train plugin

### ISSUE THREAD

**Issue by sciencey-sanjay** [newcontext-oss/kitchen-terraform#383]
I'm using to kitchen-terraform to test ruby scripts for terraform deployment. I've upgraded to Inspec 4.18.51 and kitchen-terraform 5.1.1. While I run kitchen verify, I get following error:

```
I, [2020-01-30T23:31:18.156814 #721]  INFO -- Kitchen: -----> Starting Test Kitchen (v2.3.4)
I, [2020-01-30T23:31:19.867352 #721]  INFO -- Kitchen: -----> Verifying <testsuite-ubuntu>...
W, [2020-01-30T23:31:19.919744 #721]  WARN -- Kitchen: Running command `terraform output -json` in directory /usr/app/test/fixtures/wrapper
E, [2020-01-30T23:31:22.344435 #721] ERROR -- Kitchen: ------Exception-------
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Verify failed on instance <testsuite-ubuntu>.  Please see .kitchen/logs/testsuite-ubuntu.log for more details
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: ----------------------
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: ------Backtrace-------
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:184:in `report_errors'
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:175:in `run_action'
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command/action.rb:36:in `block in call'
E, [2020-01-30T23:31:22.344462 #721] ERROR -- Kitchen: /usr/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2020-01-30T23:31:22.344469 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command/action.rb:34:in `call'
E, [2020-01-30T23:31:22.345518 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/cli.rb:52:in `perform'
E, [2020-01-30T23:31:22.345674 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
E, [2020-01-30T23:31:22.345717 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2020-01-30T23:31:22.345757 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2020-01-30T23:31:22.345796 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2020-01-30T23:31:22.345834 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2020-01-30T23:31:22.345872 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/bin/kitchen:13:in `block in <top (required)>'
E, [2020-01-30T23:31:22.345909 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2020-01-30T23:31:22.345946 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/bin/kitchen:13:in `<top (required)>'
E, [2020-01-30T23:31:22.345983 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/bin/kitchen:23:in `load'
E, [2020-01-30T23:31:22.346903 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/bin/kitchen:23:in `<top (required)>'
E, [2020-01-30T23:31:22.346937 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
E, [2020-01-30T23:31:22.346970 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
E, [2020-01-30T23:31:22.347003 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
E, [2020-01-30T23:31:22.347036 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
E, [2020-01-30T23:31:22.347069 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
E, [2020-01-30T23:31:22.347101 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
E, [2020-01-30T23:31:22.347134 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
E, [2020-01-30T23:31:22.347159 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
E, [2020-01-30T23:31:22.347196 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
E, [2020-01-30T23:31:22.347229 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
E, [2020-01-30T23:31:22.347262 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
E, [2020-01-30T23:31:22.347294 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
E, [2020-01-30T23:31:22.347327 #721] ERROR -- Kitchen: /usr/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
E, [2020-01-30T23:31:22.347361 #721] ERROR -- Kitchen: /usr/bin/bundle:23:in `load'
E, [2020-01-30T23:31:22.347393 #721] ERROR -- Kitchen: /usr/bin/bundle:23:in `<main>'
E, [2020-01-30T23:31:22.347426 #721] ERROR -- Kitchen: ----End Backtrace-----
E, [2020-01-30T23:31:22.347458 #721] ERROR -- Kitchen: -Composite Exception--
E, [2020-01-30T23:31:22.347489 #721] ERROR -- Kitchen: Class: Kitchen::InstanceFailure
E, [2020-01-30T23:31:22.347521 #721] ERROR -- Kitchen: Message: Verify failed on instance <testsuite-ubuntu>.  Please see .kitchen/logs/testsuite-ubuntu.log for more details
E, [2020-01-30T23:31:22.347563 #721] ERROR -- Kitchen: ----------------------
E, [2020-01-30T23:31:22.347599 #721] ERROR -- Kitchen: ------Backtrace-------
E, [2020-01-30T23:31:22.347631 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/kitchen-terraform-5.1.1/lib/kitchen/verifier/terraform.rb:109:in `rescue in call'
E, [2020-01-30T23:31:22.347664 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/kitchen-terraform-5.1.1/lib/kitchen/verifier/terraform.rb:102:in `call'
E, [2020-01-30T23:31:22.347697 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:459:in `block in verify_action'
E, [2020-01-30T23:31:22.347729 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-01-30T23:31:22.347763 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-01-30T23:31:22.347795 #721] ERROR -- Kitchen: /usr/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2020-01-30T23:31:22.347827 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:513:in `action'
E, [2020-01-30T23:31:22.347859 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:451:in `verify_action'
E, [2020-01-30T23:31:22.347892 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-01-30T23:31:22.347924 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-01-30T23:31:22.347957 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-01-30T23:31:22.347989 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `each'
E, [2020-01-30T23:31:22.348021 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-01-30T23:31:22.348063 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:162:in `verify'
E, [2020-01-30T23:31:22.348099 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `public_send'
E, [2020-01-30T23:31:22.348132 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-01-30T23:31:22.348174 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2020-01-30T23:31:22.348208 #721] ERROR -- Kitchen: ----End Backtrace-----
E, [2020-01-30T23:31:22.348240 #721] ERROR -- Kitchen: ---Nested Exception---
E, [2020-01-30T23:31:22.348272 #721] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2020-01-30T23:31:22.348305 #721] ERROR -- Kitchen: Message: local: Can't find train plugin aws. Please install it first.
E, [2020-01-30T23:31:22.348337 #721] ERROR -- Kitchen: ----------------------
E, [2020-01-30T23:31:22.348369 #721] ERROR -- Kitchen: ------Backtrace-------
E, [2020-01-30T23:31:22.348401 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/kitchen-terraform-5.1.1/lib/kitchen/verifier/terraform.rb:109:in `rescue in call'
E, [2020-01-30T23:31:22.348433 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/kitchen-terraform-5.1.1/lib/kitchen/verifier/terraform.rb:102:in `call'
E, [2020-01-30T23:31:22.349364 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:459:in `block in verify_action'
E, [2020-01-30T23:31:22.349404 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-01-30T23:31:22.349438 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-01-30T23:31:22.349470 #721] ERROR -- Kitchen: /usr/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2020-01-30T23:31:22.349502 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:513:in `action'
E, [2020-01-30T23:31:22.349535 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:451:in `verify_action'
E, [2020-01-30T23:31:22.349580 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-01-30T23:31:22.349614 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-01-30T23:31:22.349646 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-01-30T23:31:22.349679 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `each'
E, [2020-01-30T23:31:22.349711 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-01-30T23:31:22.349743 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:162:in `verify'
E, [2020-01-30T23:31:22.349776 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `public_send'
E, [2020-01-30T23:31:22.349808 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-01-30T23:31:22.349841 #721] ERROR -- Kitchen: /usr/app/.bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2020-01-30T23:31:22.349873 #721] ERROR -- Kitchen: ----End Backtrace-----

```

**Comment by finferflu** [comment]
Hi @sciencey-sanjay,

Please try to lock down the version of Inspec to `4.18.51`. In `Gemfile` add:

```
gem 'inspec', '4.18.51'
```

Then run `bundle update inspec`. This has fixed my issue, let's see if it fixes yours too.

**Comment by aaron-lane** [comment]
Hi @sciencey-sanjay! Thank you for your interest in the project. I apologize for the delay in responding, and for the frustrating experience. Are you able to share a repository which reproduces this issue? There have been similar problems like #351 in which the available logs did not accurately portray the root cause of the error.

**Comment by aaron-lane** [comment]
@sciencey-sanjay please reopen this issue if you can provide more information to help reproduce the problem!
