### ISSUE TITLE
Kitchen Terraform fails with Inspec 4.18.84

### ISSUE THREAD

**Issue by finferflu** [newcontext-oss/kitchen-terraform#384]
Kitchen Terraform was suddenly failing with the following error:

```
E, [2020-02-11T15:52:58.923193 #856] ERROR -- kt-suite-aws: Verify failed on instance <kt-suite-aws>.
E, [2020-02-11T15:52:58.923328 #856] ERROR -- kt-suite-aws: ------Exception-------
E, [2020-02-11T15:52:58.923353 #856] ERROR -- kt-suite-aws: Class: Kitchen::ActionFailed
E, [2020-02-11T15:52:58.923370 #856] ERROR -- kt-suite-aws: Message: remote: undefined method `resource' for :nope!:Symbol
E, [2020-02-11T15:52:58.923386 #856] ERROR -- kt-suite-aws: ----------------------
E, [2020-02-11T15:52:58.923402 #856] ERROR -- kt-suite-aws: ------Backtrace-------
E, [2020-02-11T15:52:58.923417 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/kitchen-terraform-5.1.1/lib/kitchen/verifier/terraform.rb:109:in `rescue in call'
E, [2020-02-11T15:52:58.923433 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/kitchen-terraform-5.1.1/lib/kitchen/verifier/terraform.rb:102:in `call'
E, [2020-02-11T15:52:58.923449 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:459:in `block in verify_action'
E, [2020-02-11T15:52:58.923465 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:552:in `synchronize_or_call'
E, [2020-02-11T15:52:58.923481 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:514:in `block in action'
E, [2020-02-11T15:52:58.923497 #856] ERROR -- kt-suite-aws: /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2020-02-11T15:52:58.923513 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:513:in `action'
E, [2020-02-11T15:52:58.923528 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:451:in `verify_action'
E, [2020-02-11T15:52:58.923544 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2020-02-11T15:52:58.923559 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2020-02-11T15:52:58.923575 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2020-02-11T15:52:58.923591 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `each'
E, [2020-02-11T15:52:58.923606 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:380:in `transition_to'
E, [2020-02-11T15:52:58.923622 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/instance.rb:162:in `verify'
E, [2020-02-11T15:52:58.923637 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `public_send'
E, [2020-02-11T15:52:58.923653 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:198:in `run_action_in_thread'
E, [2020-02-11T15:52:58.923669 #856] ERROR -- kt-suite-aws: /opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/2.5.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
```

I was able to fix this issue by regressing to version `4.18.51` of Inspec (not sure if this can be related in any way to issue #383).

**Comment by laurensknoll** [comment]
I'm also running into this issue when loading inspec-aws profile dependencies. Regressing to the previous release indeed resolves the issues.

When looking at the changes from inspec 4.18.51 -> 4.18.85 (current release) I see many changes regarding the LibraryEvalContext and Resources: https://github.com/inspec/inspec/pull/4814

The LibraryEvalContext [file](https://github.com/inspec/inspec/pull/4814/files#diff-40e74ce294b3e78f93b3079ec77da7ff) in particular has undergone refactoring. Comparing old and current code I notice the "LibraryEvalContext::Inspec" class constant. Previously this was an anonymous class constant, which allowed for setting an "Inspec" per class and, implicitly, it's single instance.

I'm not sure if this causes the error though, but I'm not seeing any nope! assignments anywhere else so we'll have to debug it to get to the real cause.

**Comment by aaron-lane** [comment]
It looks like InSpec has released a fix for the issue!

For posterity, the inspec gem can be pinned in `gems.rb` or `Gemfile` to work around issues like this in the future:

```rb
gem "inspec", "4.18.51"
gem "kitchen-terraform", "~> 5.2"
```
