### ISSUE TITLE
Wrong number of arguments error on bundle exec kitchen converge

### ISSUE THREAD

**Issue by sshcherbakov** [newcontext-oss/kitchen-terraform#476]
I am following the Getting Started [tutorial](https://newcontext-oss.github.io/kitchen-terraform/getting_started.html) on a MacOS 12.6.1. 
```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin21]

$ terraform --version
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/google v4.43.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

The tutorial commands work until the 
```
bundle exec kitchen converge
```
which fails with
```
$ bundle exec kitchen converge
-----> Starting Test Kitchen (v2.12.0)
Traceback (most recent call last):
	49: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	48: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	47: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/bin/kitchen:23:in `<main>'
	46: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/bin/kitchen:23:in `load'
	45: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/bin/kitchen:11:in `<top (required)>'
	44: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/errors.rb:170:in `with_friendly_errors'
	43: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/bin/kitchen:11:in `block in <top (required)>'
	42: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	41: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	40: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	38: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
	37: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:52:in `perform'
	36: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:33:in `call'
	35: from /Users/sshcherbakov/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
	34: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:34:in `block in call'
	33: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:139:in `parse_subcommand'
	32: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:109:in `filtered_instances'
	31: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:116:in `instances'
	30: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `build_instances'
	29: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `with_index'
	28: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `map'
	27: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:143:in `block in build_instances'
	26: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:250:in `new_instance'
	25: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:235:in `new_driver'
	24: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/driver.rb:37:in `for_plugin'
	23: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/plugin.rb:35:in `load'
	22: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/test-kitchen-2.12.0/lib/kitchen/plugin.rb:35:in `require'
	21: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/kitchen-terraform-5.8.0/lib/kitchen/driver/terraform.rb:19:in `<top (required)>'
	20: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/kitchen-terraform-5.8.0/lib/kitchen/driver/terraform.rb:19:in `require'
	19: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/kitchen-terraform-5.8.0/lib/kitchen/terraform/config_attribute/backend_configurations.rb:18:in `<top (required)>'
	18: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/kitchen-terraform-5.8.0/lib/kitchen/terraform/config_attribute/backend_configurations.rb:18:in `require'
	17: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/kitchen-terraform-5.8.0/lib/kitchen/terraform/config_attribute_type/hash_of_symbols_and_strings.rb:17:in `<top (required)>'
	16: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/kitchen-terraform-5.8.0/lib/kitchen/terraform/config_attribute_type/hash_of_symbols_and_strings.rb:17:in `require'
	15: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation.rb:39:in `<top (required)>'
	14: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation.rb:39:in `require'
	13: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema.rb:6:in `<top (required)>'
	12: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema.rb:6:in `require'
	11: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema/key.rb:1:in `<top (required)>'
	10: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema/key.rb:1:in `require'
	 9: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema/dsl.rb:1:in `<top (required)>'
	 8: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema/dsl.rb:1:in `require'
	 7: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema/rule.rb:1:in `<top (required)>'
	 6: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/schema/rule.rb:1:in `require'
	 5: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/deprecations.rb:4:in `<top (required)>'
	 4: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/deprecations.rb:5:in `<module:Dry>'
	 3: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/deprecations.rb:6:in `<module:Validation>'
	 2: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-validation-0.13.3/lib/dry/validation/deprecations.rb:9:in `<module:Deprecations>'
	 1: from /Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-configurable-0.16.1/lib/dry/configurable/class_methods.rb:44:in `setting'
/Users/sshcherbakov/.rvm/gems/ruby-2.7.2/gems/dry-configurable-0.16.1/lib/dry/configurable/dsl.rb:31:in `setting': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

Doesn't look like intended behaviour.

Could you please help fixing this issue.

**Comment by sshcherbakov** [comment]
Fixed by upgrading the `kitchen-terraform` from the version 5.7 specified in the tutorial to the currently latest 6.1 in the Gemfile:
```
source "https://rubygems.org/" do
  gem "kitchen-terraform", "~> 6.1"
end
```
